server.port=9910
server.contextPath=/exams

#server.ssl.key-store=localhost.p12
#server.ssl.key-store-password=password
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=tomcat

security.oauth2.resource.userInfoUri=http://localhost:9900/user
spring.main.banner-mode=off
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/job4j_exam
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache=ERROR
logging.level.ru.checkdev=INFO

# Number of ms to wait before throwing an exception if no connection is available.
spring.datasource.tomcat.max-wait=5000
# Maximum number of active connections that can be allocated from this pool at the same time.
spring.datasource.tomcat.max-active=50
# Validate the connection before borrowing it from the pool.
spring.datasource.tomcat.test-on-borrow=true

logging.file=exam.log

spring.jmx.enabled=false

#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.type=trace

server.profile=http://localhost:9900
access.profile=9dfs23vd2

liquibase.change-log=classpath:db/liquibase-changelog.xml
