server.port=9950
server.contextPath=/interview
security.oauth2.resource.userInfoUri=http://localhost:9900/user
spring.main.banner-mode=off
logging.level.root=INFO

#server.ssl.key-store=localhost.p12
#server.ssl.key-store-password=password
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=tomcat

server.exam=http://localhost:9910/exams
server.profile=http://localhost:9900
access.profile=9dfs23vd2

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/job4j_hr
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache=ERROR
logging.level.ru.checkdev=INFO

# Number of ms to wait before throwing an exception if no connection is available.
spring.datasource.tomcat.max-wait=5000
# Maximum number of active connections that can be allocated from this pool at the same time.
spring.datasource.tomcat.max-active=50
# Validate the connection before borrowing it from the pool.
spring.datasource.tomcat.test-on-borrow=true

logging.file=interview.log

spring.jmx.enabled=false

spring.http.multipart.max-file-size=2048KB
spring.http.multipart.max-request-size=2048KB

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

server.notification=http://localhost:9920
access.notification=96GcWB8a

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:./client/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=LEGACYHTML5

spring.resources.static-locations=file:./client/
spring.resources.cache-period=0

spring.liquibase.change-log=classpath:db/liquibase-changelog.xml